services:
  structurizrlite:
    image: structurizr/lite
    container_name: structurizrlite
    volumes:
      - "./dsl:/usr/local/structurizr"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network

  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    container_name: mermaid-live-editor
    volumes:
      - ./mermaid:/app/data
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app_network

  mkdocs-material:
    build:
      context: .
      dockerfile: customMkdocsBuild
    container_name: mkdocs-material
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8082:8000"
    restart: always
    networks:
      - app_network

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "8083:8080"
    restart: always
    networks:
      - app_network

  draw:
    image: jgraph/drawio
    container_name: draw
    ports:
      - "8084:8080"
      - "8443:8443"
    restart: always
    networks:
      - app_network

  stackedit:
    image: benweet/stackedit
    container_name: stackedit
    ports:
      - "8085:8080"
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: service-splash
    ports:
      - "80:80"
    volumes:
      - ./splash:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
