version: '3.8'

services:
  structurizrlite:
    image: structurizr/lite
    container_name: structurizrlite
    volumes:
      - "./dsl:/usr/local/structurizr"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app_network

  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    platform: linux/amd64
    container_name: mermaid-live-editor
    volumes:
      - ./mermaid:/app/data
    ports:
      - "8081:8080"
    restart: always
    networks:
      - app_network

  mkdocs-material:
    build:
      context: .
      dockerfile: customMkdocsBuild
    container_name: mkdocs-material
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8083:8000"
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: service-splash
    ports:
      - "80:80"
    volumes:
      - ./splash:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - structurizrlite
      - mermaid-live-editor
      - mkdocs-material
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
