services:
  kroki:
    image: yuzutech/kroki
    container_name: kroki
    ports:
      - "7000:8000"
    restart: always
    networks:
      - network_C4Lite

  structurizrlite:
    image: structurizr/lite
    container_name: structurizrlite
    volumes:
      - "./dsl:/usr/local/structurizr"
    ports:
      - "8080:8080"
    restart: always
    networks:
      - network_C4Lite

  mermaid-live-editor:
    image: ghcr.io/mermaid-js/mermaid-live-editor
    container_name: mermaid-live-editor
    volumes:
      - ./mermaid:/app/data
    ports:
      - "8081:8080"
    restart: always
    networks:
      - network_C4Lite

  mkdocs-material:
    build:
      context: .
      dockerfile: customMkdocsBuild
    container_name: mkdocs-material
    volumes:
      - ./mkdocs:/docs
    ports:
      - "8082:8000"
    restart: always
    networks:
      - network_C4Lite

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    ports:
      - "8083:8080"
    restart: always
    networks:
      - network_C4Lite

  draw:
    image: jgraph/drawio
    container_name: draw
    ports:
      - "8084:8080"
      - "8443:8443"
    restart: always
    networks:
      - network_C4Lite

  stackedit:
    image: benweet/stackedit
    container_name: stackedit
    ports:
      - "8085:8080"
    restart: always
    networks:
      - network_C4Lite

  niolesk:
    image: "ghcr.io/webgiss/niolesk"
    ports:
      - "8086:80"
    hostname: "niolesk"
    restart: "always"
    environment:
      - "NIOLESK_KROKI_ENGINE=http://localhost:8000"    
    networks:
      - network_C4Lite

  it-tools:
    image: ghcr.io/corentinth/it-tools:latest
    container_name: it-tools
    ports:
      - "8087:80"
    restart: unless-stopped
    networks:
      - network_C4Lite

  nginx:
    image: nginx:latest
    container_name: service-splash
    ports:
      - "80:80"
    volumes:
      - ./splash:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - network_C4Lite

networks:
  network_C4Lite:
    driver: bridge
